// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKa2w9LzFLhWlxIkuRn1Ju7wvoU0-2z-g',
    appId: '1:302314529023:web:18f174a5d5f28011c1acca',
    messagingSenderId: '302314529023',
    projectId: 'shop-app-ee95c',
    authDomain: 'shop-app-ee95c.firebaseapp.com',
    storageBucket: 'shop-app-ee95c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAE70HeRQAv72q7oeGBM0pAEK6n10VKuk',
    appId: '1:302314529023:android:95e20c6fbff2a45cc1acca',
    messagingSenderId: '302314529023',
    projectId: 'shop-app-ee95c',
    storageBucket: 'shop-app-ee95c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEsevoOK_axBF1jYtzkr3bSTjX28N18E',
    appId: '1:302314529023:ios:63025636995870f1c1acca',
    messagingSenderId: '302314529023',
    projectId: 'shop-app-ee95c',
    storageBucket: 'shop-app-ee95c.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEsevoOK_axBF1jYtzkr3bSTjX28N18E',
    appId: '1:302314529023:ios:972757238061a7f2c1acca',
    messagingSenderId: '302314529023',
    projectId: 'shop-app-ee95c',
    storageBucket: 'shop-app-ee95c.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
